### ISSUE TITLE
Upload to supermarket?

### ISSUE THREAD

**Issue by chino** [jasonwbarnett/ca-certificates-cookbook#1]
It would be nice if this was up on supermarket?

**Comment by bcg62** [comment]
+1

**Comment by jasonwbarnett** [comment]
ack. I will do this this weekend.

**Comment by chino** [comment]
Great thanks!

**Comment by jasonwbarnett** [comment]
As usual the supermarket is a pain in the ass to interact with... I even tried resetting my private key and it still does not work _sigh_

```
[2016/01/31 9:15:16] user@host ~ $ knife cookbook site share ca-certificates "Operating Systems & Virtualization"
Generating metadata for ca-certificates from /var/folders/tc/20xb0t9x4xb5k8jqr_7gj_d40000gn/T/chef-ca-certificates-build20160131-65352-19dv00p/ca-certificates/metadata.rb
Making tarball ca-certificates.tgz
ERROR: Authentication failed due to an invalid public/private key pair. If you have changed your keys recently try logging out and logging back in to Supermarket.
```

**Comment by chino** [comment]
Did you try to login to the site?

**Comment by jasonwbarnett** [comment]
@chino yes, I followed the directions in the error message :)

**Comment by jasonwbarnett** [comment]
Additionally I made a comment on an outstanding issue with the supermarket which may or may not be related to this issue.

https://github.com/chef/supermarket/issues/1165

**Comment by jasonwbarnett** [comment]
It's uploaded now... Please don't hesitate to submit feature requests/bugs/etc

https://supermarket.chef.io/cookbooks/ca-certificates

**Comment by chino** [comment]
Oh great thanks!
